on:
  push:
    branches:
    - dev
  workflow_dispatch:

jobs:
  deploy:
    name: deploy to dev
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
